In [29]:
#Testing the logic for moving through pooling windows

import numpy as np

poolFactor = 2
inputWidth = 4
inputHeight = 6

a = np.arange(inputWidth*inputHeight).reshape(inputHeight, inputWidth)
print a
print np.shape(a), '\n'

outputWidth = inputWidth/poolFactor
outputHeight = inputHeight/poolFactor

outputVolume = np.zeros((outputHeight,outputWidth))

for i in range(outputHeight):
    for j in range(outputWidth):
        subset = a[i*poolFactor:i*poolFactor+poolFactor, j*poolFactor:j*poolFactor+poolFactor]
        print subset
        maxVal = np.amax(subset)
        print 'maxVal:', maxVal, '\n'
        outputVolume[i,j] = maxVal

print outputVolume
print np.shape(outputVolume)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(6, 4) 

[[0 1]
 [4 5]]
maxVal: 5 

[[2 3]
 [6 7]]
maxVal: 7 

[[ 8  9]
 [12 13]]
maxVal: 13 

[[10 11]
 [14 15]]
maxVal: 15 

[[16 17]
 [20 21]]
maxVal: 21 

[[18 19]
 [22 23]]
maxVal: 23 

[[  5.   7.]
 [ 13.  15.]
 [ 21.  23.]]
(3, 2)


In [43]:
#Testing the logic for flattening the 3D input to 1D for the first FC layer
import numpy as np

inputDepth = 4
inputHeight = 3
inputWidth = 2

numOutNeurons = 7

inputVolume = np.arange(inputWidth*inputHeight*inputDepth).reshape(inputDepth, inputHeight, inputWidth)
print inputVolume
print np.shape(inputVolume)

X = inputVolume.ravel().reshape(1, (inputDepth*inputHeight*inputWidth))
print X
print np.shape(X) #shape: 1x24

W = np.random.rand((inputWidth*inputHeight*inputDepth), numOutNeurons)
Z = np.dot(X, W)

print Z
print np.shape(Z)
print np.maximum(0,Z)
print len(Z[0])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
(1, 24)
[[ 140.20863687   92.97414782  141.08503707  154.92862825  138.26696741
   115.46376076  168.4432607 ]]
(1, 7)
[[ 140.20863687   92.97414782  141.08503707  154.92862825  138.26696741
   115.46376076  168.4432607 ]]
7
